export const ACTIONS = {
  SIGNUP: "SIGNUP",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  ADD_TO_CART: "ADD_TO_CART",
  INCREASE_ITEM_COUNT: "INCREASE_ITEM_COUNT",
  DECREASE_ITEM_COUNT: "DECREASE_ITEM_COUNT",
  SEARCH_PRODUCT: "SEARCH_PRODUCT",
  ADD_ADDRESS: "ADD_ADDRESS",
};
